services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql-notification-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_security_template_dev
      MYSQL_USER: iago
      MYSQL_PASSWORD: jalim
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: