spring:

  application:
    name: spring-security-template

  datasource:
    url: jdbc:mysql://localhost:3307/spring_security_template_dev
    username: iago
    password: jalim

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO


